DROP TABLE PROFESORES, ASIGNATURAS, IMPARTE;
CREATE TABLE PROFESORES(
    dni VARCHAR(10),
    nombre VARCHAR(40),
    categoria VARCHAR(4),
    ingreso DATE,

    CONSTRAINT PK_PROFESORES PRIMARY KEY(dni)
);

CREATE TABLE ASIGNATURAS(
    codigo VARCHAR(5),
    descripcion VARCHAR(35),
    creditos DECIMAL(4,1),
    creditosp DECIMAL(4,1),

    CONSTRAINT PK_ASIGNATURAS PRIMARY KEY(codigo)
);

CREATE TABLE IMPARTE(
    dni VARCHAR(10),
    asignatura VARCHAR(5),

    CONSTRAINT PK_IMPARTE PRIMARY KEY(dni, asignatura),
    CONSTRAINT FK_IMPARTE__PROFESORES FOREIGN KEY(dni) REFERENCES PROFESORES(dni),
    CONSTRAINT FK_IMPARTE__ASIGNATURAS FOREIGN KEY(asignatura) REFERENCES ASIGNATURAS(codigo)
    
    
);